image: maven:3.6.3-jdk-11

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  dependencies:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS verify
    - mkdir /builds/valentin-apostu/artifacts
    - cp -R /builds/valentin-apostu/serenity-cucumber-petstore/target/site/serenity /builds/valentin-apostu/artifacts
  artifacts:
    when: always
    paths:
      - /builds/valentin-apostu/artifacts
    expire_in: 30 days